### ISSUE TITLE
Script checking for common interesting files on a server

### ISSUE THREAD

**Issue by Te-k** [Te-k/analyst-scripts#6]
git, htaccess, svn, test, logs, static...

**Comment by joelanders** [comment]
You've seen it, but for reference, https://github.com/hannob/snallygaster does some of those.

**Comment by Te-k** [comment]
Ah really nice tool, thanks !
I actually ended up doing this script with a limited number of file names : https://github.com/Te-k/analyst-scripts/blob/master/http/fun_files.txt
